#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance lightnet-cloud
	procd_set_param command /usr/sbin/lightnet-cloud loop
	procd_set_param respawn 3600 5 5
	procd_close_instance
}
